"""empty message

Revision ID: 041e106aa52a
Revises: b4ba6e271894
Create Date: 2023-01-29 09:42:49.183362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041e106aa52a'
down_revision = 'b4ba6e271894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
