"""password 

Revision ID: 1912d8ea5411
Revises: 9fc577bbff63
Create Date: 2023-03-03 21:06:24.637025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1912d8ea5411'
down_revision = '9fc577bbff63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Password', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['Password'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('Password')

    # ### end Alembic commands ###
