"""password 

Revision ID: 9fc577bbff63
Revises: 041e106aa52a
Create Date: 2023-03-03 18:51:32.947117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc577bbff63'
down_revision = '041e106aa52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=50), nullable=False),
    sa.Column('Name', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Name'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('actors',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('actors',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.drop_table('password')
    # ### end Alembic commands ###
